[project]
name = "leetcode-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.3",
    "pytest>=8.3.4",
    "pandas",
]

[tool.pytest.ini_options]
pythonpath = ["."]
